version: "2"
volumes:
  pgdata:
  cache:
services:
  postgres:
    image: "openmaptiles/postgis:2.9"
    volumes:
    - pgdata:/var/lib/postgresql/data
    networks:
    - postgres_conn
    ports:
     - "5432"
    env_file: .env
  import-natural-earth:
    image: "gbif/import-natural-earth:latest"
    env_file: .env
    networks:
    - postgres_conn
  import-water:
    image: "gbif/import-water:latest"
    env_file: .env
    networks:
    - postgres_conn
  import-lakelines:
    image: "gbif/import-lakelines:latest"
    env_file: .env
    networks:
    - postgres_conn
  import-osm:
    image: "gbif/import-osm:latest"
    env_file: .env
    environment:
      DIFF_MODE: ${DIFF_MODE}
    networks:
    - postgres_conn
    volumes:
     - ./data:/import
     - ./build:/mapping
     - cache:/cache
  import-osmborder:
    image: "gbif/import-osmborder:latest"
    env_file: .env
    networks:
    - postgres_conn
  import-osm-diff:
    image: "gbif/import-osm:latest"
    env_file: .env
    command: ./import_diff.sh
    environment:
      DIFF_MODE: ${DIFF_MODE}
    networks:
    - postgres_conn
    volumes:
     - ./data:/import
     - ./build:/mapping
     - cache:/cache
  update-osm:
    image: "gbif/import-osm:latest"
    env_file: .env
    environment:
      DIFF_MODE: ${DIFF_MODE}
    command: ./import_update.sh
    networks:
    - postgres_conn
    volumes:
     - ./data:/import
     - ./build:/mapping
     - cache:/cache
  import-sql:
    image: "openmaptiles/import-sql:0.6"
    env_file: .env
    networks:
    - postgres_conn
    volumes:
     - ./build:/sql
  openmaptiles-tools:
    image: "openmaptiles/openmaptiles-tools:0.6"
    env_file: .env
    networks:
    - postgres_conn
    volumes:
     - .:/tileset
     - ./build:/sql
  mapbox-studio:
    image: "osm2vectortiles/mapbox-studio"
    volumes:
     - ./build/openmaptiles.tm2source:/projects/openmaptiles.tm2source
    networks:
     - postgres_conn
    ports:
     - "3000:3000"
  generate-changed-vectortiles:
    image: "openmaptiles/generate-vectortiles:0.1.1"
    command: ./export-list.sh
    volumes:
    - ./data:/export
    - ./build/openmaptiles.tm2source:/tm2source
    networks:
    - postgres_conn
    env_file: .env
  generate-vectortiles:
    image: "openmaptiles/generate-vectortiles:0.1.1"
    volumes:
    - ./data:/export
    - ./build/openmaptiles.tm2source:/tm2source
    networks:
    - postgres_conn
    env_file: .env
    environment:
      #BBOX: "8.25,46.97,9.58,47.52"
      #BBOX: "5.97,45.75,10.7,47.72"
      BBOX: ${BBOX}
      MIN_ZOOM: ${MIN_ZOOM}
      MAX_ZOOM: ${MAX_ZOOM}
  postserve:
    image: "openmaptiles/postserve:0.2"
    env_file: .env
    networks:
     - postgres_conn
    ports:
    - "8090:8080"
    volumes:
     - ./build/openmaptiles.tm2source:/mapping
  tilestache-server:
    image: "gbif/tilestache-vectortiles"
    ports:
     - 8000:8000
     - 8787:8787
    command: ./run-server.sh
    volumes:
     - ./export:/export
     - ./build:/mapping
    networks:
    - postgres_conn
    env_file: .env
  tilestache-server-3575:
    image: "gbifmaptiles/tilestache"
    ports:
     -  3575:8000
     - 13575:8787
    command: ./run-server.sh
    volumes:
     - ./export:/data/export
     - ./gbifmaptiles:/data/tilestache
    networks:
    - postgres_conn
    env_file: .env
    environment:
      LAYER: "EPSG:3575"
  tilestache-seed:
    image: "gbifmaptiles/tilestache"
    command: ./export-local.sh
    volumes:
     - ./export:/data/export
     - ./gbifmaptiles:/data/tilestache
    networks:
    - postgres_conn
    env_file: .env
    environment:
      # Whole world
      LAYER: "EPSG:4326"
      BBOX: "-89.9999 -179.9999 89.9999 179.9999"
      MIN_ZOOM: "0"
      MAX_ZOOM: "5"

networks:
  postgres_conn:
    driver: bridge
